### ISSUE TITLE
[OSC] Feature request : world info read / send

### ISSUE THREAD

**Issue by NovaVoidHowl** [kafeijao/Kafe_CVR_Mods#24]
It would be good to have a world endpoint set like the following   
```yaml
world:
    id: read to get the current guid of the world, write to switch world
    status: (all are readonly)
      - flying_allowed: (bool)
      - noclip_allowed: (bool)
      - props_allowed: (bool)
      - portals_allowed: (bool)
      - number_of_users: (int)
      - number_of_props: (int) 
      - instance id: (string)
```

The reason for this is to allow OSC apps to behave differently depending on world conditions.  
  
*Example 1*, have a contact on the arm of your avatar, and in worlds that allow props have it spawn in a prop menu for avatar config, but in world that does not allow props the same contact would cause a smaller less feature rich on avatar menu to become active.   

*Example 2*, have a contact on the arm of your avatar which would in worlds that permit it toggle flight mode, and in worlds that don't would cause a warning message to be shown (or indeed disable the contact and provide visual representation on the avatar ie. change a texture)
