### ISSUE TITLE
[OSC] Feature request : AAS menu endpoint

### ISSUE THREAD

**Issue by NovaVoidHowl** [kafeijao/Kafe_CVR_Mods#25]
The idea is to permit AAS menu entries to be updated via OSC.  
the endpoint layout could be something like this.  

```yaml
QuickMenu:  
    AAS_menu:  
      menu_open: (bool) read to get state of menu, write to open/close menu  
      menu_count: (int | readonly) number of menu items in the AAS list  
      param_list: (list of sub endpoints) for parrams in the menu, read to get/write to set.  
                        list content can be a mix of bool/int/float/trigger      
```
